name: Publish app on Homey
on:
  workflow_dispatch:

jobs:
  main:
    name: Publish app on Homey
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@olivierzal'
          cache: 'npm'
      - name: Publish
        uses: OlivierZal/github-action-homey-app-publish@patch-1
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
